name: Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'  # Runs only when Terraform files are modified
    branches:
      - main
      - 'feature/**'

  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform Action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-plan:
    name: Terraform Plan & Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Format Check
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Save Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform/tfplan

  terraform-approval:
    name: Manual Approval
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
    - name: Await Manual Approval
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-actors: "highelf"  # Replace with your GitHub username
        comment: "Terraform plan is ready. Approve to apply changes."

  terraform-apply:
    name: Terraform Apply
    needs: terraform-approval
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'apply' || github.event_name == 'push'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan
        path: terraform/

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    needs: terraform-approval
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Destroy
      working-directory: terraform
      run: terraform destroy -auto-approve
